# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to Sean Tank Garvey's Site!
email: seanthetankgarvey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  As I Journey From Total Beginner With Zero Experience To My End Goal of Being A Programmer/Coder And Being, TRULY, A WEBMASTER,
  This website was created by Sean Tank Garvey (and publiblished) in 2017 with two main purposes...
  ONE. To Share/Teach The Information I've Learned.  TWO. And To Share My Personal Struggles and Successes With The World. 
#3. To Experiment With Writing A Blog That Promotes Temporary Failures As A Successful Learning Method And To See The Response!
#  The Plan: Learn How To- Create Sites in HTML, Test Webpages(.html files) Within Browsers for Errors, Design What I Want Pages To Look Like, 
#  Style Sites in CSS to Match My/Others' Design Wants, Code in HTML5 (tags) instead of standard HTML, Program Webpages in JavaScript, 
#  Make Responsive Websites (Designs) Using BootStrap, Perfect Website SEO (Search Engine Optimization) = ultimately, MASTER WEBSITE DEVELOPMENT. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://www.CoderSG.com" # the base hostname & protocol for your site
twitter_username: SeanTankGarvey
github_username:  SeanTankGarvey

# Build settings
markdown: kramdown
